---

# Create Staging Folder
- name: Create Staging Folder
  file:
    path: /build-artifacts/
    state: directory

- name: Display ansible pkg mgr fact value
  ansible.builtin.debug:
    msg:
    - "the ansible_pkg_mgr is {{ ansible_pkg_mgr }}"

- name: Copy installer files to remote server
  copy:
    src: "{{ role_path }}/files/{{ fireeye_package }}"
    dest: "/build-artifacts/{{ fireeye_package }}"

- name: Install FireEye using yum if package manager is yum
  yum:
    name: /build-artifacts/{{ fireeye_package }}
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Install FireEye using apt if package manager is apt
  apt:
    deb: /build-artifacts/{{ fireeye_package }}
  when: ansible_pkg_mgr == "apt"

- name: Install FireEye using yum if package manager is dnf
  yum:
    name: /build-artifacts/{{ fireeye_package }}
    state: present
  when: ansible_pkg_mgr == "dnf"

- name: Remove the FireEye installer 
  file:
    path: /build-artifacts/{{ fireeye_package }}
    state: absent

# Configure FireEye service
- name: Configure FireEye
  template:
    src: agent_config.json.j2
    dest: /var/lib/fireeye/xagt/agent_config.json

- name: run fireeye config
  shell: /opt/fireeye/bin/xagt -i /var/lib/fireeye/xagt/agent_config.json
  args:
    creates: /var/lib/fireeye/xagt/main.db

- name: Enable and start service xagt
  service:
    name: xagt
    state: stopped
    enabled: yes

