---

# Checks if the service is already installed and running as a service
- name: Check if service exists
  win_service:
    name: xagt
  register: result
  ignore_errors: yes

- name: Remove a service
  ansible.windows.win_service:
    name: xagt
    state: absent
  when: result is defined and (result.state is not defined or result.name is not defined)
  ignore_errors: yes

- name: Download FireEye Agent from S3
  win_command: "PowerShell.exe -Command Read-S3Object -BucketName {{ fireeye_s3_bucket }} -Key {{ fireeye_s3_prefix }}/{{ fireeye_package }} -File c:\\Temp\\FireEyeAgent.zip"

- name: Unzip FireEyeAgent.zip
  win_unzip:
    src: C:\Temp\FireEyeAgent.zip
    dest: C:\Temp\FireEyeAgent
    delete_archive: yes

- name: Install an FireEye agent
  win_package:
    path: C:\Temp\FireEyeAgent\xagtSetup_32.30.0_universal.msi
    arguments: /qn

# Configure FireEye service
- name: Configure FireEye
  win_template:
    src: agent_config.json.j2
    dest: C:\Program Files (x86)\FireEye\xagt\agent_config.json

- name: Run fireeye with configuration
  win_command: '"C:\Program Files (x86)\FireEye\xagt\xagt.exe" -i "C:\Program Files (x86)\FireEye\xagt\agent_config.json"'

- name: Set service startup mode to auto and ensure it is started
  win_service:
    name: xagt
    start_mode: auto
    state: started

- name: Check if service is running
  win_service:
    name: xagt
  register: result
  ignore_errors: yes

- name: Stop Service
  win_service:
    name: xagt
    state: stopped
  when: result is defined and (result.state is not defined or result.name is not defined)
  ignore_errors: yes
