---

# Checks if the service is already installed and running as a service
- name: Check if service exists
  win_service:
    name: xagt
  register: result
  ignore_errors: yes

- name: Remove a service
  ansible.windows.win_service:
    name: xagt
    state: absent
  when: result is defined and (result.state is not defined or result.name is not defined)
  ignore_errors: yes

# Create Staging Folder
- name: Create Staging Folder
  win_file:
    path: C:\build-artifacts
    state: directory

- name: Copy installer files to remote server
  win_copy:
    src: "{{ role_path }}/files/{{ fireeye_package }}"
    dest: "C:\\build-artifacts\\{{ fireeye_package }}"

# Configure FireEye service
- name: Configure FireEye
  win_template:
    src: agent_config.json.j2
    dest: C:\build-artifacts\agent_config.json

- name: Install an FireEye agent
  win_package:
    path: "C:\\build-artifacts\\{{ fireeye_package }}"
    arguments: /qn

- name: Set service startup mode to auto and ensure it is started
  win_service:
    name: xagt
    start_mode: auto
    state: started
  ignore_errors: yes

- name: Check if service is running
  win_service:
    name: xagt
  register: result
  ignore_errors: yes

- name: Stop Service
  win_service:
    name: xagt
    state: stopped
  when: result is defined and (result.state is not defined or result.name is not defined)
  ignore_errors: yes
